### ISSUE TITLE
Learn isn't connecting to server

### ISSUE THREAD

**Issue by majormatt28** [learn-co-curriculum/programming-univbasics-nds-nested-arrays-lab-1#1]
Hi my learn ide isn't connecting back to the server and has been trying to reconnect for the last 20 mins. I'm unsure if this is the right place to file this under. Please let me know if there is something that could be done. Thank you.

**Comment by lizbur10** [comment]
Hi there - sorry to hear you're having difficulties!

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) is primarily used to report problems with the curriculum — typos or other errors.

The issue you're experiencing would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

Thanks and good luck! 💙
